language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
after_success:
  - npm install -g travis-deploy-once@4
  - travis-deploy-once "yarn deploy"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/